
// All mock data and functions previously in this file have been migrated to 
// their respective database services and API routes.

// You can retain utility functions if they are truly generic and not tied to mock data structures.
// For example, getShortenerDomain might still be used as a fallback if no custom domain is present on a link,
// though the linkService.ts now primarily handles domain resolution for short URLs.

let shortenerDomain = process.env.NEXT_PUBLIC_SHORTENER_DOMAIN || 'linkyle.com'; 

export const getShortenerDomain = (): string => {
  return shortenerDomain;
};

export const setShortenerDomain = (domain: string) => {
  shortenerDomain = domain || 'linkyle.com';
};

// If you had a generic generateMockId, it's no longer needed as UUIDs are generated by services.

// Mock user profile functions are also removed as user data is handled by NextAuth and potentially a userService.

console.log("src/lib/mock-data.ts is now clean of specific entity mock data.");

