services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DB_TYPE: ${DB_TYPE:-postgres} 
        POSTGRES_URI: ${POSTGRES_URI} # Changed from POSTGRES_URL
        DATABASE_URL: ${DATABASE_URL} 
        NEXT_PUBLIC_SHORTENER_DOMAIN: ${NEXT_PUBLIC_SHORTENER_DOMAIN}
        NEXTAUTH_URL: ${NEXTAUTH_URL}
        NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
        PORT: ${PORT:-3000}
    container_name: shorten_it
    # Remove direct port mapping, Traefik will handle this
    # ports:
    #   - "3000:3000"
    env_file:
      - .env 
    environment:
      - NODE_ENV=production
      - PORT=${PORT:-3000} 
      # POSTGRES_URL should be in your .env file, e.g.:
      # POSTGRES_URL=postgresql://user:password@db:5432/shorten_it_db
      # DB_TYPE=postgres # Should also be in .env
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.port=${PORT:-3000}"
      - "traefik.http.routers.lnked.rule=Host(`lnker.me`)"
      - "traefik.http.routers.lnked.entrypoints=https"
      - "traefik.http.routers.lnked.tls.certresolver=letsencrypt"
      - "traefik.http.services.lnked.loadbalancer.server.port=${PORT:-3000}"
      - "traefik.http.middlewares.lnked.headers.accesscontrolalloworiginlist=*"
networks:
  proxy:
    external: true

