import { DB_TYPE, pool, clientPromise } from '../../scripts/db'; // Assuming similar DB setup
import { Collection, Db, ObjectId } from 'mongodb';

export type ConsentType = 
  | 'TERMS_AND_PRIVACY_ACKNOWLEDGEMENT' // For initial sign-up
  | 'ANALYTICS_PROCESSING'          // For general analytics
  | 'MARKETING_EMAILS'              // Example for future use
  // ... other specific consent types as needed
  ;

export interface UserConsent {
  id?: string;         // Optional for MongoDB as _id will be used
  _id?: ObjectId;      // MongoDB specific ID
  userId: string;      // Foreign key to User model
  consentType: ConsentType;
  isGiven: boolean;    // True if consent is given, false if explicitly withdrawn or declined
  timestamp: Date;     // Last updated timestamp of this consent status
  // source?: string;   // Optional: Where was consent given (e.g., 'registration', 'account_settings', 'banner')
}

// MongoDB collection and helper functions (similar to other models)
let userConsentsCollection: Collection<UserConsent> | null = null;

async function getMongoUserConsentsCollection(): Promise<Collection<UserConsent>> {
  if (userConsentsCollection) {
    return userConsentsCollection;
  }
  if (!clientPromise) {
    throw new Error('MongoDB client promise not initialized');
  }
  const client = await clientPromise;
  const db: Db = client.db();
  userConsentsCollection = db.collection<UserConsent>('user_consents');
  await userConsentsCollection.createIndex({ userId: 1, consentType: 1 }, { unique: true });
  return userConsentsCollection;
}

export const UserConsentModel = {
  async findByUserAndType(userId: string, consentType: ConsentType): Promise<UserConsent | null> {
    if (DB_TYPE === 'mongodb') {
      const collection = await getMongoUserConsentsCollection();
      return collection.findOne({ userId, consentType });
    } else if (DB_TYPE === 'postgres') {
      if (!pool) throw new Error('PostgreSQL pool not initialized.');
      const res = await pool.query('SELECT id, "userId", "consentType", "isGiven", timestamp FROM user_consents WHERE "userId" = $1 AND "consentType" = $2', [userId, consentType]);
      return res.rows[0] || null;
    }
    throw new Error('Unsupported DB_TYPE');
  },

  async upsert(userId: string, consentType: ConsentType, isGiven: boolean): Promise<UserConsent> {
    const now = new Date();
    if (DB_TYPE === 'mongodb') {
      const collection = await getMongoUserConsentsCollection();
      const result = await collection.findOneAndUpdate(
        { userId, consentType },
        { $set: { isGiven, timestamp: now }, $setOnInsert: { userId, consentType, createdAt: now } }, // createdAt example for MongoDB
        { upsert: true, returnDocument: 'after' }
      );
      if (!result) throw new Error('MongoDB upsert failed for user consent');
      // Ensure the returned document matches the UserConsent interface, especially if _id is involved.
      // The 'result' object from findOneAndUpdate includes the _id. We map it to 'id' if needed or ensure UserConsent handles _id.
      const updatedDoc = await collection.findOne({ _id: result?._id }); // Re-fetch to ensure proper mapping if needed or trust the returned doc
      if (!updatedDoc) throw new Error('Failed to retrieve consent document after upsert.');
      const { _id, ...rest } = updatedDoc;
      return { id: _id.toHexString(), ...rest };

    } else if (DB_TYPE === 'postgres') {
      if (!pool) throw new Error('PostgreSQL pool not initialized.');
      // Assumes 'id' is auto-generated by Postgres (e.g., SERIAL or UUID default)
      // If 'id' is not auto-generated, it needs to be provided or handled differently.
      // The schema provided uses gen_random_uuid() which is good.
      const res = await pool.query(
        `INSERT INTO user_consents ("userId", "consentType", "isGiven", timestamp)
         VALUES ($1, $2, $3, $4)
         ON CONFLICT ("userId", "consentType") DO UPDATE SET
           "isGiven" = EXCLUDED."isGiven",
           timestamp = EXCLUDED.timestamp
         RETURNING id, "userId", "consentType", "isGiven", timestamp`,
        [userId, consentType, isGiven, now]
      );
      return res.rows[0];
    }
    throw new Error('Unsupported DB_TYPE');
  },
  
  async findAllByUserId(userId: string): Promise<UserConsent[]> {
    if (DB_TYPE === 'mongodb') {
        const collection = await getMongoUserConsentsCollection();
        const consents = await collection.find({ userId }).toArray();
        return consents.map(doc => {
            const { _id, ...rest } = doc;
            return { id: _id.toHexString(), ...rest };
        });
    } else if (DB_TYPE === 'postgres') {
        if (!pool) throw new Error('PostgreSQL pool not initialized.');
        const res = await pool.query('SELECT id, "userId", "consentType", "isGiven", timestamp FROM user_consents WHERE "userId" = $1', [userId]);
        return res.rows;
    }
    throw new Error('Unsupported DB_TYPE');
  }
};
